version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: pongdb
      POSTGRES_USER: ponguser
      POSTGRES_PASSWORD: pongpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: ./pong_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./pong_backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pgdata: